FROM ubuntu:17.10

LABEL version="1.2"
ENV VERSION="1.2"

#Create volumes inside image
VOLUME /opt/robotframework/project
VOLUME /opt/robotframework/reports

#Install tools
RUN   apt-get update -y \
      && apt-get install -y \
      python-pip \
      wget \
      libglu1 \
      xvfb \
      nano \
      curl \
      openssh-client \
      build-essential \
      libssl-dev \ 
      libffi-dev python-dev \
      libgconf-2-4
      
#Install Firefox 
RUN apt-get install -y firefox
      
#Install latest Chromium
RUN apt-get install -y chromium-browser

#Install robotframework and related libraries
RUN   pip install  \
      selenium==3.4.3 \
      robotframework==3.0.2 \
      robotframework-selenium2library==1.8.0 \
      robotframework-requests==0.4.7 \
      requests==2.14.2 \
      robotframework-xvfb==1.2.2 \
      robotframework-httplibrary==0.4.2 \
      robotframework-sshlibrary==2.1.3 \
      paramiko==2.2.1 \
      webdriver-manager \
      python-dateutil

#Replace chromium-browser binary with launch script with additional parameters
RUN  mv /usr/bin/chromium-browser /usr/bin/chromium-browser-original \
     && ln -sfv /opt/robotframework/bin/google-chrome /usr/bin/chromium-browser

#Clean up and remove temporary files
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


#Add entrypoint script
#COPY /bin/docker-entrypoint.sh /opt/robotframework/bin/

#Copy chrome launcher script including additional parameters
#COPY /bin/chromium-browser.sh /opt/robotframework/bin/google-chrome

#Set environment variables
#ENV PATH=/opt/robotframework/bin:/opt/robotframework/drivers:$PATH
#ENV robot_testpath=Tests/API/Rest/
#ENV robot_pythonpath=lib/
#ENV robot_argumentfile=Configurations/

#Container launch script / can be overriden with exec command when launching
#CMD ["docker-entrypoint.sh"]
